language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO_VERSION=1.7.5

# command to install dependencies

install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: python principal/tests.py